# Generated by Django 4.0.4 on 2022-04-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipselbucket', '0003_comment_created_at_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnipsels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snipsels', models.ManyToManyField(to='snipselbucket.snipsel')),
            ],
        ),
    ]
